// task-manager/src/components/Header.svelte
<div class="header">
    <h1>Task manager</h1>
</div>

<style lang="scss">
    .header {
        background: linear-gradient(90deg, #663399, #9f5afd);
        padding: 10px 20px;

        h1 {
            font-family: "header";
            color: white;
            text-shadow: 3px 3px #444;
            font-size: 250%;
        }
    }
</style>

// tv-search/src/components/Header.vue
<template>
  <div id="header">
    <img :src="logo" alt="Logo do TV Search" />
    <span>TV Search</span>
  </div>
</template>

<script lang="ts">
import logo from "../assets/img/logo64.png";

export default {
  data: () => {
    return {
      logo,
    };
  },
};
</script>

<style lang="scss" scoped>
@import "../globals";

#header {
  background-color: $background-color;
  padding: 20px 10px;

  * {
    vertical-align: middle;
  }

  span {
    margin-left: 20px;
    color: white;
    font-family: "secondary";
    font-size: 300%;
  }
}
</style>
